# Generated by Django 2.2.2 on 2019-09-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trainername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerName',
            new_name='Trainer',
        ),
    ]
