# Generated by Django 2.2.5 on 2019-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190926_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainerImage',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='static/'),
        ),
    ]
