# Generated by Django 2.2.5 on 2019-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190926_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainerImage',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pro_pic'),
        ),
    ]
