# Generated by Django 2.2.5 on 2019-09-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190926_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toEmailList', models.CharField(max_length=1000)),
                ('fromEmail', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('bodyEmail', models.CharField(max_length=2500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
