# Generated by Django 2.2.5 on 2019-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_myy'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Test',
            },
        ),
    ]
