# Generated by Django 2.2.5 on 2019-10-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
